_wandb:
    value:
        cli_version: 0.24.1
        e:
            qsle55z9bwommd2najjouo1asqfhd7mi:
                args:
                    - --config_path=/gemini/code/VideoX-Fun/config/wan2.2/wan_civitai_5b.yaml
                    - --pretrained_model_name_or_path=/gemini/code/models/Wan2.2-Fun-5B-InP
                    - --dataset_type=robot
                    - --robot_data_root=/gemini/code/datasets/libero/perturbed
                    - --robot_suites
                    - libero_90
                    - libero_10
                    - libero_goal
                    - libero_object
                    - libero_spatial
                    - --libero_data_root=/gemini/code/datasets/LIBERO-Cosmos-Policy/success_only
                    - --image_sample_size=256
                    - --video_sample_size=256
                    - --enable_bucket
                    - --token_sample_size=256
                    - --video_sample_stride=1
                    - --video_sample_n_frames=45
                    - --train_batch_size=32
                    - --gradient_accumulation_steps=1
                    - --dataloader_num_workers=0
                    - --num_train_epochs=10000
                    - --checkpointing_steps=500
                    - --save_state
                    - --resume_from_checkpoint=latest
                    - --learning_rate=1e-04
                    - --seed=42
                    - --output_dir=/gemini/code/VideoX-Fun/scripts/closed_loop_wan2.2_fun/output_dir_robot_libero
                    - --gradient_checkpointing
                    - --mixed_precision=bf16
                    - --adam_weight_decay=3e-2
                    - --adam_epsilon=1e-10
                    - --vae_mini_batch=1
                    - --max_grad_norm=0.05
                    - --random_hw_adapt
                    - --training_with_video_token_length
                    - --uniform_sampling
                    - --boundary_type=full
                    - --rank=128
                    - --network_alpha=128
                    - --target_name=q,k,v,ffn.0,ffn.2
                    - --use_peft_lora
                    - --train_mode=inpaint
                    - --low_vram
                codePath: scripts/closed_loop_wan2.2_fun/train_lora_robot.py
                codePathLocal: scripts/closed_loop_wan2.2_fun/train_lora_robot.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "7679364128768"
                        used: "845224534016"
                email: WYW3276027@126.com
                executable: /gemini/code/envs/videoxfun/bin/python3.10
                git:
                    commit: d0fcc4d459251be653c516490fa7493bee7bf496
                    remote: https://github.com/aigc-apps/VideoX-Fun.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-c57b6cb4-f7f7-47d2-0bc7-6ff4a23a91ec
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-17d4d72d-4a05-9acf-824a-f43aca0f42c5
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-d99ae3b3-b33c-a413-29fb-2bab3162752c
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-75294cc1-5551-bfe8-8c90-013fc1a1e194
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-0683d04c-bb94-86ca-88de-e61c43070e90
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-13ef0c41-4f3b-c2f7-67fd-27116149ead7
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-b300c66d-f093-6c1b-da06-a93cf9820a17
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-c5c2e0fb-d841-1919-dcaf-30ed663f10d1
                host: 57379c90f99b68a651dff647fd9ff962-taskrole1-0
                memory:
                    total: "2164298846208"
                os: Linux-4.18.0-348.el8.x86_64-x86_64-with-glibc2.35
                program: /gemini/code/VideoX-Fun/scripts/closed_loop_wan2.2_fun/train_lora_robot.py
                python: CPython 3.10.0
                root: /gemini/code/VideoX-Fun
                startedAt: "2026-02-02T10:23:01.369011Z"
                writerId: qsle55z9bwommd2najjouo1asqfhd7mi
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 80
                - 83
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 80
                - 83
                - 98
                - 105
            "3":
                - 61
            "4": 3.10.0
            "5": 0.24.1
            "6": 4.57.1
            "12": 0.24.1
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-10
adam_weight_decay:
    value: 0.03
allow_tf32:
    value: false
auto_tile_batch_size:
    value: false
boundary_type:
    value: full
cache_dir:
    value: null
checkpointing_steps:
    value: 500
checkpoints_total_limit:
    value: null
config_path:
    value: /gemini/code/VideoX-Fun/config/wan2.2/wan_civitai_5b.yaml
dataloader_num_workers:
    value: 0
dataset_type:
    value: robot
enable_bucket:
    value: true
enable_text_encoder_in_dataloader:
    value: false
fix_sample_size:
    value: null
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: true
hub_model_id:
    value: null
hub_token:
    value: null
image_sample_size:
    value: 256
input_perturbation:
    value: 0
keep_all_node_same_token_length:
    value: false
learning_rate:
    value: 0.0001
libero_data_root:
    value: /gemini/code/datasets/LIBERO-Cosmos-Policy/success_only
libero_first_frame_prob:
    value: 0.1
local_rank:
    value: 0
logging_dir:
    value: logs
logit_mean:
    value: 0
logit_std:
    value: 1
lora_skip_name:
    value: null
low_vram:
    value: true
lr_scheduler:
    value: constant
lr_warmup_steps:
    value: 500
max_grad_norm:
    value: 0.05
max_train_samples:
    value: null
max_train_steps:
    value: 60000
mixed_precision:
    value: bf16
mode_scale:
    value: 1.29
motion_sub_loss:
    value: false
motion_sub_loss_ratio:
    value: 0.25
multi_stream:
    value: false
network_alpha:
    value: 128
noise_offset:
    value: 0
non_ema_revision:
    value: null
num_train_epochs:
    value: 10000
output_dir:
    value: /gemini/code/VideoX-Fun/scripts/closed_loop_wan2.2_fun/output_dir_robot_libero
pair_sep:
    value: null
prediction_type:
    value: null
pretrained_model_name_or_path:
    value: /gemini/code/models/Wan2.2-Fun-5B-InP
push_to_hub:
    value: false
random_flip:
    value: false
random_frame_crop:
    value: false
random_hw_adapt:
    value: true
random_ratio_crop:
    value: false
rank:
    value: 128
report_to:
    value: wandb
resume_from_checkpoint:
    value: latest
revision:
    value: null
robot_data_root:
    value: /gemini/code/datasets/libero/perturbed
robot_source_data_root:
    value: /gemini/code/datasets/libero/datasets
save_state:
    value: true
scale_lr:
    value: false
seed:
    value: 42
snr_loss:
    value: false
target_name:
    value: q,k,v,ffn.0,ffn.2
token_sample_size:
    value: 256
tokenizer_max_length:
    value: 512
tracker_project_name:
    value: wan_vla
train_batch_size:
    value: 32
train_data_dir:
    value: null
train_data_meta:
    value: null
train_mode:
    value: inpaint
train_sampling_steps:
    value: 1000
train_text_encoder:
    value: false
training_with_video_token_length:
    value: true
transformer_path:
    value: null
uniform_sampling:
    value: true
use_8bit_adam:
    value: false
use_came:
    value: false
use_deepspeed:
    value: false
use_ema:
    value: false
use_fsdp:
    value: false
use_peft_lora:
    value: true
use_white_frame:
    value: false
vae_mini_batch:
    value: 1
vae_path:
    value: null
validation_data_jsonl:
    value: null
validation_epochs:
    value: 50000
validation_prompts:
    value: null
validation_steps:
    value: 200
variant:
    value: null
video_repeat:
    value: 0
video_root:
    value: null
video_sample_n_frames:
    value: 45
video_sample_size:
    value: 256
video_sample_stride:
    value: 1
weighting_scheme:
    value: none
